Fix goss tests because with actual goss version 0.3.5 the exec attribute in command is not recognized:
Error: Invalid Attribute for Command:permission-cas-plugin: command